import React, { useState, useEffect, forwardRef, useImperativeHandle } from 'react';
import { DocumentEditor } from '@onlyoffice/document-editor-react';

export interface VexiusPdfEditorProps {
  documentId: string;
  navbarElement?: React.ReactNode;
  sidebar?: React.ReactNode;
}

export interface VexiusPdfEditorRef {
  getFullText: () => string;
  getCurrentSelection: () => string;
  applyAction: (text: string) => void;
}

export const VexiusPdfEditor = forwardRef<VexiusPdfEditorRef, VexiusPdfEditorProps>(({ documentId, navbarElement, sidebar }, ref) => {
  const [editorConfig, setEditorConfig] = useState<any>(null);
  const [isCopilotVisible, setIsCopilotVisible] = useState(true);

  useEffect(() => {
    const handleToggleAI = () => setIsCopilotVisible(prev => !prev);
    window.addEventListener('vexius:toggle-ai', handleToggleAI as EventListener);
    return () => window.removeEventListener('vexius:toggle-ai', handleToggleAI as EventListener);
  }, []);

  useEffect(() => {
    const fetchConfig = async () => {
      try {
        const token = localStorage.getItem("vexius_token");
        const apiUrl = process.env.NEXT_PUBLIC_API_URL;
        
        // Fetch the ONLYOFFICE configuration generated by our backend
        const res = await fetch(`${apiUrl}/documents/${documentId}/editor-config`, {
          headers: {
            "Authorization": `Bearer ${token}`
          }
        });
        
        if (res.ok) {
          const config = await res.json();
          setEditorConfig(config);
        }
      } catch (e) {
        console.error("Failed to fetch ONLYOFFICE config", e);
      }
    };
    fetchConfig();
  }, [documentId]);

  useImperativeHandle(ref, () => ({
    getFullText: () => "", // Handled server-side or via ONLYOFFICE plugins
    getCurrentSelection: () => "", // Handled server-side or via ONLYOFFICE plugins
    applyAction: () => {}
  }));

  const onDocumentReady = () => {
    console.log("ONLYOFFICE PDF Editor is ready");
  };

  if (!editorConfig) {
    return <div style={{ padding: '24px' }}>Loading PDF Editor...</div>;
  }

  const documentServerUrl = process.env.NEXT_PUBLIC_ONLYOFFICE_URL;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', width: '100%', background: '#f3f4f6' }}>
      {/* 
        We use ONLYOFFICE's built-in toolbar, so we might not need the custom VexiusPdfRibbon here,
        but we keep the navbarElement if provided for consistency (like breadcrumbs).
      */}
      {navbarElement}
      
      {/* Vexius AI Toolbar for ONLYOFFICE */}
      <div style={{ display: 'flex', padding: '6px 16px', background: '#fff', borderBottom: '1px solid #e5e7eb', alignItems: 'center', justifyContent: 'flex-end' }}>
        <button onClick={() => window.dispatchEvent(new CustomEvent('vexius:toggle-ai'))} style={{ 
          border: isCopilotVisible ? '1px solid #a855f7' : '1px solid #e5e7eb',
          background: isCopilotVisible ? '#f3e8ff' : '#fff', 
          borderRadius: '6px', padding: '6px 12px', 
          display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer',
          boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)'
        }}>
          <img src="/logo.png" alt="Vexius AI" style={{ width: '20px', height: '20px', objectFit: 'contain' }} />
          <span style={{ fontSize: '0.875rem', color: isCopilotVisible ? '#9333ea' : '#374151', fontWeight: 600 }}>Vexius AI Copilot</span>
        </button>
      </div>

      <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
        
        {/* Left Sidebar (AI Copilot) */}
        {isCopilotVisible && sidebar && (
          <div style={{ 
            width: '320px', 
            flexShrink: 0, 
            background: '#fff', 
            borderRight: '1px solid #e5e7eb',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden'
          }}>
            {sidebar}
          </div>
        )}

        {/* Main ONLYOFFICE Editor Area */}
        <div style={{ flex: 1, position: 'relative' }}>
          <DocumentEditor
            id={`pdfEditor-${documentId}`}
            documentServerUrl={documentServerUrl || ""}
            config={editorConfig}
            events_onDocumentReady={onDocumentReady}
            height="100%"
            width="100%"
          />
        </div>
      </div>
    </div>
  );
});

VexiusPdfEditor.displayName = "VexiusPdfEditor";
